services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: GMAIL_USER
        fromService:
          type: secret
          name: gmail_user
      - key: GMAIL_APP_PASSWORD
        fromService:
          type: secret
          name: gmail_app_password
    plan: free
